spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://47.92.241.17:3306/oauth2server?characterEncoding=UTF-8&useSSL=false
    username: oauth2server
    password: 2t#svzPYp3RS
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  redis:
    database: 2
    host: 47.92.241.17
    port: 9865
    password: 7YfN#Dk54w25r3
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 6001


management:
  endpoint:
    health:
      enabled: true




