server:
  port: 3601
spring:
  security:
    user:
      name: admin
      password: admin

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
