spring:
  application:
    name: consul-config
server:
  port: 5008


management:
  endpoints:
    health:
      sensitive: false
    restart:
      enabled: false
    shutdown:
      enabled: false

